// Comptabilite Constants

// Loading
export const START_LOADING_COMPATIBILITE = "START_LOADING_COMPATIBILITE";
export const STOP_LOADING_COMPATIBILITE = "STOP_LOADING_COMPATIBILITE";

// Fetch
export const COMPATIBILITE_FETCH_ITEM_REQUEST =
  "COMPATIBILITE_FETCH_ITEM_REQUEST";
export const COMPATIBILITE_FETCH_ITEM_SUCCESS =
  "COMPATIBILITE_FETCH_ITEM_SUCCESS";
export const COMPATIBILITE_FETCH_ITEM_FAILURE =
  "COMPATIBILITE_FETCH_ITEM_FAILURE";

// Add
export const COMPATIBILITE_ADD_ITEM_REQUEST = "COMPATIBILITE_ADD_ITEM_REQUEST";
export const COMPATIBILITE_ADD_ITEM_SUCCESS = "COMPATIBILITE_ADD_ITEM_SUCCESS";
export const COMPATIBILITE_ADD_ITEM_FAILURE = "COMPATIBILITE_ADD_ITEM_FAILURE";

// update
export const COMPATIBILITE_UPDATE_ITEM_REQUEST =
  "COMPATIBILITE_UPDATE_ITEM_REQUEST";
export const COMPATIBILITE_UPDATE_ITEM_SUCCESS =
  "COMPATIBILITE_UPDATE_ITEM_SUCCESS";
export const COMPATIBILITE_UPDATE_ITEM_FAILURE =
  "COMPATIBILITE_UPDATE_ITEM_FAILURE";

// delete
export const COMPATIBILITE_DELETE_ITEM_REQUEST =
  "COMPATIBILITE_DELETE_ITEM_REQUEST";
export const COMPATIBILITE_DELETE_ITEM_SUCCESS =
  "COMPATIBILITE_DELETE_ITEM_SUCCESS";
export const COMPATIBILITE_DELETE_ITEM_FAILURE =
  "COMPATIBILITE_DELETE_ITEM_FAILURE";

// Suggestions
export const COMPATIBILITE_FETCH_ITEMS_FOR_SUGGESTION_REQUEST =
  "COMPATIBILITE_FETCH_ITEMS_FOR_SUGGESTION_REQUEST";
export const COMPATIBILITE_FETCH_ITEMS_FOR_SUGGESTION_SUCCESS =
  "COMPATIBILITE_FETCH_ITEMS_FOR_SUGGESTION_SUCCESS";
export const COMPATIBILITE_FETCH_ITEMS_FOR_SUGGESTION_FAILURE =
  "COMPATIBILITE_FETCH_ITEMS_FOR_SUGGESTION_FAILURE";

// CLEARE LOGISTIC STORE

export const CLEAR_COMPATIBILITE_STORE = "CLEAR_COMPATIBILITE_STORE";
