export const FETCH_USERS_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_USERS_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_USERS_FAILURE = "FETCH_DATA_FAILURE";

export const BOLCK_USER_REQUEST = "BOLCK_USER_REQUEST";
export const BOLCK_USER_SUCCESS = "BOLCK_USER_SUCCESS";
export const BOLCK_USER_FAILURE = "BOLCK_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURESS";

export const CLOSE_ADD_USER_FORM = "CLOSE_ADD_USER_FORM";
export const CLOSE_ADD_USER_FORM_SUCCESS = "CLOSE_ADD_USER_FORM_SUCCESS";

export const CLOSE_EDIT_USER_FORM = "CLOSE_EDIT_USER_FORM";
export const CLOSE_EDIT_USER_FORM_SUCCESS = "CLOSE_EDIT_USER_FORM_SUCCESS";

export const OPEN_ADD_USER_FORM = "OPEN_ADD_USER_FORM";
export const OPEN_EDIT_USER_FORM = "OPEN_EDIT_USER_FORM";
