export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const START_LOADING = "START_LOADING";

// export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
// export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
// export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
