export const FETCH_LISTES_DE_BASE = "FETCH_LISTES_DE_BASE";
export const FETCH_LISTES_DE_BASE_SUCCESS = "FETCH_LISTES_DE_BASE_SUCCESS";
export const FETCH_LISTES_DE_BASE_FAILURE = "FETCH_LISTES_DE_BASE_FAILURE";
export const UPDATE_LISTES_DE_BASE = "UPDATE_LISTES_DE_BASE";
export const UPDATE_LISTES_DE_BASE_SUCCESS = "UPDATE_LISTES_DE_BASE_SUCCESS";
export const UPDATE_LISTES_DE_BASE_FAILURE = "UPDATE_LISTES_DE_BASE_FAILURE";

export const FETCH_DEVISE = "FETCH_DEVISE";
export const FETCH_DEVISE_SUCCESS = "FETCH_DEVISE_SUCCESS";
export const FETCH_DEVISE_FAILURE = "FETCH_DEVISE_FAILURE";

export const CHANGE_BRANCH = "CHANGE_BRANCH";

// Loading
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
