export const FETCH_FOURNISSEURS_SUCCESS = "FETCH_FOURNISSEURS_SUCCESS";
export const FETCH_FOURNISSEURS_REQUEST = "FETCH_FOURNISSEURS_REQUEST";
export const FETCH_FOURNISSEURS_FAILURE = "FETCH_FOURNISSEURS_FAILURE";

export const START_LOADING_FOURNISSEURS = "START_LOADING_FOURNISSEURS";

export const DELETE_FOURNISSEUR_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_FOURNISSEUR_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_FOURNISSEUR_FAILURE = "DELETE_ARTICLE_FAILURE";
