//= ====================================
//  EMAIL AUTH
//-------------------------------------

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const PASSWORD_FORGET_REQUEST = "PASSWORD_FORGET_REQUEST";
export const PASSWORD_FORGET_SUCCESS = "PASSWORD_FORGET_SUCCESS";
export const PASSWORD_FORGET_FAILURE = "PASSWORD_FORGET_FAILURE";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SYNC_USER = "SYNC_USER";

export const HIDE_MSG = "HIDE_MSG";

export const SET_UID = "SET_UID";
export const SET_TOKEN = "SET_TOKEN";

export const LOADING = "LOADING";
export const STOPLOADING = "STOPLOADING";
