// logistique Constants

// Loading
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

// Fetch
export const FETCH_ITEM_REQUEST = "FETCH_ITEM_REQUEST";
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_FAILURE = "FETCH_ITEM_FAILURE";

export const LOGISTIC_FETCH_UNITES_REQUEST = "LOGISTIC_FETCH_UNITES_REQUEST";
export const LOGISTIC_FETCH_UNITES_SUCCESS = "LOGISTIC_FETCH_UNITES_SUCCESS";
export const LOGISTIC_FETCH_UNITES_FAILURE = "LOGISTIC_FETCH_UNITES_FAILURE";

// Add
export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

// update
export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";

// delete
export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";

// Suggestions
export const FETCH_ITEMS_FOR_SUGGESTION_REQUEST =
  "FETCH_ITEMS_FOR_SUGGESTION_REQUEST";
export const FETCH_ITEMS_FOR_SUGGESTION_SUCCESS =
  "FETCH_ITEMS_FOR_SUGGESTION_SUCCESS";
export const FETCH_ITEMS_FOR_SUGGESTION_FAILURE =
  "FETCH_ITEMS_FOR_SUGGESTION_FAILURE";

// CLEARE LOGISTIC STORE

export const CLEARE_LOGISTIC_STORE = "CLEARE_LOGISTIC_STORE";
