// logistique Constants

// ARTICLE
export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILURE = "ADD_ARTICLE_FAILURE";

// Loading
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const FETCH_CATEGORIE_REQUEST = "FETCH_CATEGORIE_REQUEST";
export const FETCH_CATEGORIE_SUCCESS = "FETCH_CATEGORIE_SUCCESS";
export const FETCH_CATEGORIE_FAILURE = "FETCH_CATEGORIE_FAILURE";

export const FETCH_CATEGORIE_DESIGNATIONS_REQUEST =
  "FETCH_CATEGORIE_DESIGNATIONS_REQUEST";
export const FETCH_CATEGORIE_DESIGNATIONS_SUCCESS =
  "FETCH_CATEGORIE_DESIGNATIONS_SUCCESS";
export const FETCH_CATEGORIE_DESIGNATIONS_FAILURE =
  "FETCH_CATEGORIE_DESIGNATIONS_FAILURE";

export const FETCH_ARTICLES_FOR_SUGGESTION_REQUEST =
  "FETCH_ARTICLES_FOR_SUGGESTION_REQUEST";
export const FETCH_ARTICLES_FOR_SUGGESTION_SUCCESS =
  "FETCH_ARTICLES_FOR_SUGGESTION_SUCCESS";
export const FETCH_ARTICLES_FOR_SUGGESTION_FAILURE =
  "FETCH_ARTICLES_FOR_SUGGESTION_FAILURE";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILURE = "UPDATE_ARTICLE_FAILURE";

export const FETCH_ARTICLE_REQUEST = "FETCH_ARTICLE_REQUEST";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILURE";

// Fetch
export const FETCH_ITEM_REQUEST = "FETCH_ITEM_REQUEST";
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_FAILURE = "FETCH_ITEM_FAILURE";

// Add
export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

// update
export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";

// Suggestions
export const FETCH_ITEMS_FOR_SUGGESTION_REQUEST =
  "FETCH_ITEMS_FOR_SUGGESTION_REQUEST";
export const FETCH_ITEMS_FOR_SUGGESTION_SUCCESS =
  "FETCH_ITEMS_FOR_SUGGESTION_SUCCESS";
export const FETCH_ITEMS_FOR_SUGGESTION_FAILURE =
  "FETCH_ITEMS_FOR_SUGGESTION_FAILURE";
