// logistique Constants

// ARTICLE
export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILURE = "ADD_ARTICLE_FAILURE";

// Loading
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

// CATEGORIE
export const ADD_CATEGORIE_REQUEST = "ADD_CATEGORIE_REQUEST";
export const ADD_CATEGORIE_SUCCESS = "ADD_CATEGORIE_SUCCESS";
export const ADD_CATEGORIE_FAILURE = "ADD_CATEGORIE_FAILURE";

export const FETCH_CATEGORIE_REQUEST = "FETCH_CATEGORIE_REQUEST";
export const FETCH_CATEGORIE_SUCCESS = "FETCH_CATEGORIE_SUCCESS";
export const FETCH_CATEGORIE_FAILURE = "FETCH_CATEGORIE_FAILURE";

export const FETCH_CATEGORIE_DESIGNATIONS_REQUEST =
  "FETCH_CATEGORIE_DESIGNATIONS_REQUEST";
export const FETCH_CATEGORIE_DESIGNATIONS_SUCCESS =
  "FETCH_CATEGORIE_DESIGNATIONS_SUCCESS";
export const FETCH_CATEGORIE_DESIGNATIONS_FAILURE =
  "FETCH_CATEGORIE_DESIGNATIONS_FAILURE";

export const FETCH_ARTICLES_FOR_SUGGESTION_REQUEST =
  "FETCH_ARTICLES_FOR_SUGGESTION_REQUEST";
export const FETCH_ARTICLES_FOR_SUGGESTION_SUCCESS =
  "FETCH_ARTICLES_FOR_SUGGESTION_SUCCESS";
export const FETCH_ARTICLES_FOR_SUGGESTION_FAILURE =
  "FETCH_ARTICLES_FOR_SUGGESTION_FAILURE";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_FAILURE = "UPDATE_ARTICLE_FAILURE";
